### ISSUE TITLE
Locking issue

### ISSUE THREAD

**Issue by ianarchbell** [carlk3/FreeRTOS-FAT-CLI-for-RPi-Pico#13]
Hi Carl, had to disable assertConfig on line 81 of spi.c to reliably run for 24 hours. I am not sure why yet. It seems to fail on this assert even when there is only one task reading the SD card... I had been running very well in Release mode (thank you) only discovered when I ran in debug.

**Comment by carlk3** [comment]
That would seem to indicate that an unexpected DMA interrupt was received. What else is running in the system? Any help you could provide on how to recreate the problem would be useful. It looks like this is hard coded to use DMA_IRQ_0 exclusively. I'm working on porting over the SD driver from [no-OS-FatFS-SD-SDIO-SPI-RPi-Pico](https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico), and that supports configuring the driver to use DMA_IRQ_0 or DMA_IRQ_1, shared or exclusive. 

If nothing else is using DMA, the only other explanation that I can think of is that for some reason the DMA is driving the block reception completion interrupt more than once, which I can't explain. The DMA is supposed to transfer one 512 byte block at a time.

If it's some kind of timing problem, it might be interesting to experiment with the task priorities to see if that can help reproduce the problem more easily.

**Comment by ianarchbell** [comment]
Although I have not started a web browsing session, Wi-Fi is running - kicked off in the main task - and I suspect interaction with that, sometiimes it's trying to use vprint (WiFi warning messages - this has been reported as an issue but I believe it's supposed to have been fixed) and gets into a deadlock - however that wasn't the case I reported, I have a data logger task and it's running that that causes the assertion fail - it's basically your data logger example with a couple of tweaks. I have also been getting WiFi stall messages - after about 24 hours of running. But seems to depend on the day. I will take another look at it early next week and see if can find something more definitive - I appreciate your help. As I have something demoable, even if not production I have switched over to my hardware design this week.

**Comment by carlk3** [comment]
I noticed that there is an error in line 81 of spi.c. 
```
    BaseType_t rc = ulTaskNotifyTake(pdTRUE, 0);
```
should really be 
```
    uint32_t rc = ulTaskNotifyTakeIndexed(1, pdTRUE, 0);
```

`ulTaskNotifyTake(pdTRUE, 0)` is equivalent to `ulTaskNotifyTakeIndexed(0, pdTRUE, 0)`, where the first argument is the index into the array of 'task notifications'. So, that line is clearing the wrong notification (and the assert is checking that it was not set). That still doesn't explain where the `vTaskNotifyGive` for index 0 is coming from, though.

**Comment by ianarchbell** [comment]
OK. I’ll make that change and take a look on Friday. I’ll let you know how I get on.


Sent from Yahoo Mail for iPhone


On Tuesday, October 31, 2023, 10:03 PM, Carl J Kugler III ***@***.***> wrote:




I noticed that there is an error in line 81 of spi.c.
    BaseType_t rc = ulTaskNotifyTake(pdTRUE, 0);

should really be
    uint32_t rc = ulTaskNotifyTakeIndexed(1, pdTRUE, 0);

ulTaskNotifyTake(pdTRUE, 0) is equivalent to ulTaskNotifyTakeIndexed(0, pdTRUE, 0), where the first argument is the index into the array of 'task notifications'. So, that line is clearing the wrong notification (and the assert is checking that it was not set). That still doesn't explain where the vTaskNotifyGive for index 0 is coming from, though.

**Comment by carlk3** [comment]
I have completed a first whack at porting the SD driver from [no-OS-FatFS-SD-SDIO-SPI-RPi-Pico](https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico), including SDIO support. I haven't updated the README yet, but the hardware configuration is now the same as for [no-OS-FatFS-SD-SDIO-SPI-RPi-Pico](https://github.com/carlk3/no-OS-FatFS-SD-SDIO-SPI-RPi-Pico). This is only lightly tested, but if you want to give it a try you can checkout dev branch.

**Comment by ianarchbell** [comment]
Will do Carl! Great news. And btw your change did fix the problem I was experiencing. I still have more work to do to check on the task interaction but I think that’s my problem not yours.


Sent from Yahoo Mail for iPhone


On Thursday, November 2, 2023, 6:01 PM, Carl J Kugler III ***@***.***> wrote:




I have completed a first whack at porting the SD driver from no-OS-FatFS-SD-SDIO-SPI-RPi-Pico, including SDIO support. I haven't updated the README yet, but the hardware configuration is now the same as for no-OS-FatFS-SD-SDIO-SPI-RPi-Pico. This is only lightly tested, but if you want to give it a try you can checkout dev branch.
